#!/usr/bin/env python3
"""
ccTLD Protocol Support Visualisation
Generates a choropleth map and small multiples from a technical profile CSV dataset.
"""

import sys
import os

from visualisation.data import load_data, load_world, merge_data
from visualisation.choropleth import make_interactive_map, make_static_map
from visualisation.multiples import make_small_multiples
from visualisation.counts import make_protocol_charts

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

OUTPUT_DIR = 'output'

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) != 2:
        print("Usage: python visualise.py <results.csv>")
        print("  results.csv  Path to the ccTLD technical profile CSV generated by the data gathering scripts")
        sys.exit(1)

    csv_path = sys.argv[1]

    if not os.path.exists(csv_path):
        print(f"Error: file not found: {csv_path}")
        sys.exit(1)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    df     = load_data(csv_path)
    world  = load_world()
    merged = merge_data(world, df)

    make_interactive_map(df, os.path.join(OUTPUT_DIR, 'profile_interactive.html'))
    make_static_map(merged, os.path.join(OUTPUT_DIR, 'profile_static.png'))
    make_small_multiples(merged, os.path.join(OUTPUT_DIR, 'profile_multiples.png'))
    make_protocol_charts(df, os.path.join(OUTPUT_DIR, 'protocol_counts.png'))

    print("\nDone. Outputs:")
    print(f"  {OUTPUT_DIR}/profile_interactive.html  — embeddable interactive map")
    print(f"  {OUTPUT_DIR}/profile_static.png        — static consolidated protocol support map")
    print(f"  {OUTPUT_DIR}/profile_multiples.png     — detailed graphics by category")
    print(f"  {OUTPUT_DIR}/profile_counts.png        — bar charts with counts")


if __name__ == '__main__':
    main()